### PR TITLE
Renamed file publisher plugin and updated names/imports

### PR DESCRIPTION
**Pull request by thomastaylor312**
This PR came from discussion on #1046 

Summary of changes:
- Renamed the file publisher plugin to `snap-publisher-mock-file`
- Created [new file publisher repo](https://github.com/intelsdi-x/snap-plugin-publisher-file) for non-testing file publishing
- Updated paths and meta data for the plugin

Testing done:
- Small unit tests

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by thomastaylor312** [comment]
Ok @intelsdi-x/snap-maintainers, I finally got all of the unit tests fixed. Can someone take a look at this?

**Comment by jcooklin** [comment]
The example tasks need to be updated too.

**Comment by thomastaylor312** [comment]
@jcooklin I did think about that, but my thought is that those are supposed to be used with the new file plugin, not with the mock one used for testing

**Comment by jcooklin** [comment]
Will you update the tasks that include mock in their name?  They should work with the mock file publisher.  

An argument could be made that we should reference the plugin repos for the none mock example tasks but that's outside the scope of this PR.

**Comment by thomastaylor312** [comment]
Will do

**Comment by jcooklin** [comment]
LGTM

**Comment by thomastaylor312** [comment]
Thanks @jcooklin! Merging

**Pull request merged**
