### PR TITLE
Updating plugins_catalog.md by pluginsync [ci skip]

### PR DESCRIPTION
**Pull request by nanliu**

### CODE REVIEW

**Comment by nanliu** [comment]
This is generated by the pluginsync tool per https://github.com/intelsdi-x/snap-pluginsync/pull/26

**Comment by kindermoumoute** [comment]
Would it make sense for `Maintainer` columns to redirect to gh profile instead of plugin repo?

**Comment by nanliu** [comment]
Yes, let me change the maintainer to point to the user/org profile instead of the repo.

**Comment by nanliu** [comment]
@mjbrender did you have any feedback before we merge this?

**Comment by kindermoumoute** [comment]
LGTM

**Comment by mjbrender** [comment]
File LGTM 🚢. 

One request: add a description. `no description provided` is a sad description 😢. Maybe it could summarize number of new plugins + wishlist requests.

Still, LGTM 👍

**Pull request merged**
