### PR TITLE
Added NFS client plugin to the catalog

### PR DESCRIPTION
**Pull request by thomastaylor312**
This adds the NFS client plugin to the active development section of the catalog.

### CODE REVIEW

**Comment by danielscottt** [comment]
Hey, @thomastaylor312, your fork is out of date.  Want to rebase master in and push back up?

**Comment by thomastaylor312** [comment]
@danielscottt Just finished rebasing.

**Comment by tiffanyfj** [comment]
@thomastaylor312 It's now out of date again. Can you rebase?

**Comment by thomastaylor312** [comment]
@tiffanyfj Done.

**Comment by tiffanyfj** [comment]
Thanks. Can merge after Travis passes.

**Pull request merged**
