### PR TITLE
Made REST API responses consistent (snake_case) 

### LINKED ISSUE #1172: Fix inconsistant naming in rest API
Under body of each "GET v1/xx" call the lists should all be snake_case. 

“GET /v1/tasks” needs to be consistent with similar calls such as "/v1/plugins" and "/v1/metrics". 

**"GET /v1/plugins"**

```
“body”: {
    “loaded_plugins”: [...]
}
```

**"GET /v1/tasks"**

```
“body”: {
    “ScheduledTasks”: [...]
}
```

**"GET /v1/metrics"**

```
“body”: {
    “metrics”: [...]
}
```

### PR DESCRIPTION
**Pull request by kjlyon**
Fixes #1172 

Summary of changes:
- Made list names under body consistent (snake_case) for all calls
- Updated MetricReturned and ScheduledTaskListReturned structs to include  the appropriate json tags implementing snake_case 

Testing done:
- Unit tests

@intelsdi-x/snap-maintainers

- /v1/tasks
- /v1/metrics

### CODE REVIEW

**Comment by jcooklin** [comment]
This is a breaking change and needs to be communicated/discussed more broadly before merging.

**Comment by tjmcs** [comment]
At the very least, this would be an example of exactly the sort of change that would require incrementing the version of the RESTful API (and, as such, should probably be lumped in with any other breaking changes that the team feels should be made to "clean up" what may be perceived as inconsistencies or flaws in the design of the current version of the Snap RESTful API). Just my two cents...

**Comment by lynxbat** [comment]
@bjray we need to discuss API breaking changes that are fixing errors.

**Comment by kjlyon** [comment]
This PR has been refactored and captured in #1255

**Pull request closed without merging**
