### PR TITLE
Added new plugins

### LINKED ISSUE #1413: Plugin Wanted: Elasticsearch publisher
I'd like to get a publisher that can play well with Elasticsearch. 

Elasticsearch exposes REST API which allows to create data record via POST call (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html), or modify it with PUT command (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). Basically it should be able to create new records.
Also there are few configuration options like: 
- protocol - http or https
- server address - default localhost
- server port - default 9200

All of them should be passed with task manifest configuration. There is no need to put this in global config.
There are should be possible some optional configuration options:
- user - for optional authentication
- password - for optional authentication
- path - endpoint to publish data

### PR DESCRIPTION
**Pull request by katarzyna-z**
Fixes #1413

Summary of changes:
- Added new plugins: 
    - [snap-plugin-collector-logs](https://github.com/intelsdi-x/snap-plugin-collector-logs)
    - [snap-plugin-processor-logs-openstack](https://github.com/intelsdi-x/snap-plugin-processor-logs-openstack)
    - [snap-plugin-processor-logs-regexp](https://github.com/intelsdi-x/snap-plugin-processor-logs-regexp)
   - [snap-plugin-publisher-elasticsearch](https://github.com/intelsdi-x/snap-plugin-publisher-elasticsearch)

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by andrzej-k** [comment]
Great job! Also it seems that this PR resolves #1413, so Elasticsearch publisher can be removed from the plugins wishlist.

**Comment by mjbrender** [comment]
Good call @andrzej-k - I added the `Fixed #` annotation to @katarzyna-z's description so it will close the associated issue.

**Comment by mjbrender** [comment]
One more FYI: you don't have to put the plugins in alphabetical order - the parsing process will organize it into the Plugin Catalog. 

Hey @katarzyna-z, you can merge this whenever you're ready.

**Comment by katarzyna-z** [comment]
@andrzej-k The plugin will be removed from wish after launching snap-pluginsync to generate plugin catalog.

**Comment by andrzej-k** [comment]
Thanks @katarzyna-z. LGTM

**Pull request merged**
