### PR TITLE
update sirupsen logrus import path

### PR DESCRIPTION
**Pull request by jtlisi**
Fixes https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

Summary of changes:
- update import path of sirupsen logrus

Testing done:
- `make test-all`

Related to: https://github.com/intelsdi-x/snap-plugin-lib-go/pull/97

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by IzabellaRaulin** [comment]
There is still `Sirupsen` found instead of `sirupsen` in lower-case:

```
$ make

../../../vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/plugin.go:44:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /home/iza/Projects/src/github.com/intelsdi-x/snap/vendor/github.com/Sirupsen/logrus (vendor tree)
        /root/.gvm/gos/go1.8.1/src/github.com/Sirupsen/logrus (from $GOROOT)
        /home/iza/Projects/src/github.com/Sirupsen/logrus (from $GOPATH)
../../../vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/plugin.go:44:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /home/iza/Projects/src/github.com/intelsdi-x/snap/vendor/github.com/Sirupsen/logrus (vendor tree)
        /root/.gvm/gos/go1.8.1/src/github.com/Sirupsen/logrus (from $GOROOT)
        /home/iza/Projects/src/github.com/Sirupsen/logrus (from $GOPATH)
../../../vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/plugin.go:44:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /home/iza/Projects/src/github.com/intelsdi-x/snap/vendor/github.com/Sirupsen/logrus (vendor tree)
        /root/.gvm/gos/go1.8.1/src/github.com/Sirupsen/logrus (from $GOROOT)
        /home/iza/Projects/src/github.com/Sirupsen/logrus (from $GOPATH)
2017-10-17 11:24:53 UTC [     info] building snap-plugin-collector-mock2 for linux/amd64
../../../vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/plugin.go:44:2: cannot find package "github.com/Sirupsen/logrus" in any of:
        /home/iza/Projects/src/github.com/intelsdi-x/snap/vendor/github.com/Sirupsen/logrus (vendor tree)
        /root/.gvm/gos/go1.8.1/src/github.com/Sirupsen/logrus (from $GOROOT)
        /home/iza/Projects/src/github.com/Sirupsen/logrus (from $GOPATH)
```

**Comment by jtlisi** [comment]
@IzabellaRaulin I will be sure to update this request once https://github.com/intelsdi-x/snap-plugin-lib-go/pull/97 is merged! :+1:

**Comment by WangJialei-A** [comment]
@jtlisi I have already merged the [PR](https://github.com/intelsdi-x/snap-plugin-lib-go/pull/97) in snap-lib-go. Please update snap-lib-go version in glide.lock to pass the travis ci test. Thanks for your contribution.

**Comment by jtlisi** [comment]
@WangJialei-A this should be good to go

**Pull request merged**
