### PR TITLE
adds snappy to readme

### PR DESCRIPTION
**Pull request by danielscottt**
RIP @tiffanyfj's snappy, long live happy snappy.

### CODE REVIEW

**Comment by danielscottt** [comment]
cc: @mjbrender

**Comment by tiffanyfj** [comment]
I think the full snappy turtle is better here.

**Comment by mjbrender** [comment]
+1 to @tiffanyfj's point. I dig the full one too.

**Comment by danielscottt** [comment]
Thumbs up snappy is no doubt a more chill dude, but I accept your feedback.  Full snappy it is.

**Comment by mjbrender** [comment]
@danielscottt one more request - what say you to adding one w/the text? See attached.
snappy-thumbsup-with-text
snappy-full-with-text

**Comment by danielscottt** [comment]
I’m down for either.

Thumbs-up-snappy-with-text’s game is strong.

Anyone else have a vote? @intelsdi-x/snap-maintainers

So, with reactions: :heart: for thumbs up snappy vs. :tada: for full snappy?

**Comment by thomastaylor312** [comment]
I have to say snappy above full snappy even though I like the full one better. It is just too big and distracting for a logo. Sorry full snappy...

**Comment by danielscottt** [comment]
I'm going to make the changes after lunch.  Come vote before it's too late!

**Comment by sandlbn** [comment]
I would like to have snappy sticker on the back of my laptop.

**Comment by danielscottt** [comment]
Ready for merge.

**Comment by mjbrender** [comment]
LGTM @danielscottt 

@sandlbn what office are you at? I have a ton of stickers on order for everyone.

**Comment by tiffanyfj** [comment]
@mjbrender He's in Ireland Intel Labs.

**Comment by sandlbn** [comment]
@mjbrender Yes Intel Ireland, I will send u details by mail.

**Pull request merged**
