### PR TITLE
Store build binary in S3.

### PR DESCRIPTION
**Pull request by nanliu**
Store snap travici linux builds in a s3 repository.

* Upload build directory to AWS s3.
* Update DNS build.ci.snap-telemtry.io -> s3 repo.

Testing done:

* manual

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by nanliu** [comment]
This is not ready to merge. The tests are intentionally trimmed, and we need to restore some filtering criteria before merging to master.

**Comment by IzabellaRaulin** [comment]
@nanliu, I've added a label because you wrote that is not ready to merge. Please, inform me when this pull request will be ready to merge, so I remove the label. It will be helpful if you add some checklist like [here](https://github.com/intelsdi-x/snap/pull/872) to show the status of works on that. Thank You.

**Comment by nanliu** [comment]
@IzabellaRaulin this is ready for review now.

Because of the following condition restriction, you won't see anything interesting in the travis.ci run for the pull request, only when the code is merged to master:

```
deploy:
  on:
    repo: intelsdi-x/snap
    branch: master
    condition: $SNAP_TEST_TYPE = medium && $TRAVIS_GO_VERSION = "1.6.2"
```

Due to this reason, I have a temporary build branch to demonstrate this change [here](https://travis-ci.org/intelsdi-x/snap/jobs/146170866#L466-L500). The interesting section are summarized below:

```
2016-07-20 17:49:20 UTC [     info] copying snap binaries to /home/travis/gopath/src/github.com/intelsdi-x/snap/build/snap-e373c0d
...
uploading "snap-e373c0d/snapctl" with {:content_type=>"", :acl=>"public-read"}
uploading "snap-e373c0d/snapd" with {:content_type=>"", :acl=>"public-read"}
uploading "snap-e373c0d/snap-plugin-collector-mock1" with {:content_type=>"", :acl=>"public-read"}
uploading "snap-e373c0d/snap-plugin-collector-mock2" with {:content_type=>"", :acl=>"public-read"}
uploading "snap-e373c0d/snap-plugin-processor-passthru" with {:content_type=>"", :acl=>"public-read"}
uploading "snap-e373c0d/snap-plugin-publisher-mock-file" with {:content_type=>"", :acl=>"public-read"}
...
2016-07-20 17:49:34 UTC [     info] updating package URL: https://s3-us-west-2.amazonaws.com/intelsdi-x/snap/snap-e373c0d
```

When a PR is merged on master, the last test (medium on Go 1.6.2) will:

* move the build directory to a folder containing the sha of the commit (via predeploy).
* copy the build directory to s3://intelsdi-x/snap (via deploy).
* update the dns build.ci.snap-telemetry.io to point to the latest build folder on s3 (vis postdeploy).

The will ensure the latest snap binary is available at:

* http://build.ci.snap-telemetry.io/snapctl
* http://build.ci.snap-telemetry.io/snapd
* http://build.ci.snap-telemetry.io/snap-plugin-collector-mock1
* http://build.ci.snap-telemetry.io/snap-plugin-collector-mock2
* http://build.ci.snap-telemetry.io/snap-plugin-processor-passthru
* http://build.ci.snap-telemetry.io/snap-plugin-publisher-mock-file

Older versions will be available at:
https://s3-us-west-2.amazonaws.com/intelsdi-x/snap/snap-{sha}/

NOTE: This is strictly used for internal testing, and there is neither guarantees on availability, and we have not decided how long to store old binaries.

**Comment by nanliu** [comment]
Updated to use full sha and a separate build branch. Latest build example:

https://travis-ci.org/intelsdi-x/snap/jobs/146729271#L203-L237

**Comment by IRCody** [comment]
LGTM

**Pull request merged**
