### PR TITLE
Adding more psutil for :cloud: :computer:-ing

### PR DESCRIPTION
**Pull request by mjbrender**
Making a video that includes more metrics, particularly for vm data, and want to have them in our examples.

### CODE REVIEW

**Comment by tjmcs** [comment]
it's actually a bit more than those three lines that are missing; this file also doesn't include the pass thru processor plugin...

**Comment by mjbrender** [comment]
@tjmcs noted - fixing that now.

**Comment by mjbrender** [comment]
@tjmcs I made the exact file name match the exact output, which will also be in the post. I want to keep the other example to show the difference between using a processor and not in YAML. Whatcha think?

**Comment by tjmcs** [comment]
:+1: I like the idea of having multiple examples (with and without processor) and the code shown in the video linked to from your blog posting now matches one of the files available here :)

**Comment by mjbrender** [comment]
thank you sir - merging.

**Pull request merged**
