### PR TITLE
Add unit_test task

### PR DESCRIPTION
**Pull request by bodepd**
Fixes #

Summary of changes:
- adds unit_test task

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by mjbrender** [comment]
What's happening here @bodepd ? You good?

**Comment by bodepd** [comment]
@mjbrender I'm testing the initial integration of the test jenkins system that I've built. Two jobs, based on the two golang versions that are currently specified in the .travis.yml file. Still need to figure out why these tests are failing, but getting much closer...

Plan is to allow these tests as 'opt in' (meaning they have to be triggered with the above phrase), and eventually have them triggered just like the travis tests. The eventual goal is for them to serve as either a replacement of or a complement to the travisci tests.

**Comment by nanliu** [comment]
@bodepd, you need to enable the environment variable:
```
GO15VENDOREXPERIMENT=1
```

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please retest this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please save 1.5.4

**Comment by bodepd** [comment]
please save 1.6.2

**Comment by bodepd** [comment]
please save 1.5.4

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please save 1.5.4

**Comment by bodepd** [comment]
please save 1.6.2

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test small

**Comment by bodepd** [comment]
please test small

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Comment by bodepd** [comment]
please test this

**Pull request closed without merging**
