### PR TITLE
Vendoring with Git submodules

### PR DESCRIPTION
**Pull request by elemoine**
I am opening this PR to follow up on the discussion in https://github.com/intelsdi-x/snap/issues/994.

Summary of changes:

- Used [Vandetta](https://github.com/dpw/vendetta) to populate the `vendor` directory with Git submodules for Snap's dependencies.
- Changed the submodules' commits based on the current content of `Godeps.json`.
- Removed `Godeps.json` and the associated `deps.sh` script.

This is what I've used for testing:

```
$ export GOPATH=/tmp/go
$ mkdir -p $GOPATH/src/github.com/intelsdi-x
$ cd $GOPATH/src/github.com/intelsdi-x
$ git clone -b vendor --single-branch https://github.com/elemoine/snap
$ cd snap
$ git submodule update --init --recursive
$ go install  # "make all" works as well
```

Vandetta is just used to create and update the submodules' commits. To get, build and install Snap one just uses the standard Go tools (`go get`). And by using submodules we avoid bloating the Snap repo.

### CODE REVIEW

**Comment by nanliu** [comment]
@elemoine, git cherry-pick 2c86748 from #991. interesting, you didn't add any git submodule commands and it seems to be taken care of automatically.

**Comment by elemoine** [comment]
I don't understand why we don't see the same issue in master.

**Comment by elemoine** [comment]
> interesting, you didn't add any git submodule commands and it seems to be taken care of automatically.

What di you mean? What is taken care of automatically?

**Comment by nanliu** [comment]
In travis.ci it automatically takes care of the git submodule (https://travis-ci.org/intelsdi-x/snap/jobs/139490146): 

```
$ git clone --depth=50 https://github.com/intelsdi-x/snap.git intelsdi-x/snap
Cloning into 'intelsdi-x/snap'...
remote: Counting objects: 1655, done.
remote: Compressing objects: 100% (980/980), done.
remote: Total 1655 (delta 936), reused 1210 (delta 627), pack-reused 0
Receiving objects: 100% (1655/1655), 695.64 KiB | 0 bytes/s, done.
Resolving deltas: 100% (936/936), done.
Checking connectivity... done.
$ cd intelsdi-x/snap
0.33s$ git fetch origin +refs/pull/1008/merge:
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 78 (delta 26), reused 72 (delta 21), pack-reused 0
Unpacking objects: 100% (78/78), done.
From https://github.com/intelsdi-x/snap
 * branch            refs/pull/1008/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
git.submodule
$ git submodule update --init --recursive
```

**Comment by elemoine** [comment]
> In travis.ci it automatically takes care of the git submodule

Oh yes, I knew that.

On a different topic, I still don't understand why we do not see the goimports issue on the master branch.

**Comment by lynxbat** [comment]
@intelsdi-x/snap-maintainers did we make a decision yet on vendoring?

**Comment by jcooklin** [comment]
The plan of record is to move to glide with PR #991.  

@elemoine, thanks for submitting this PR to experiment with using git submodules for checking in vendored deps.   Unless there is an objection I propose that we close this PR and move forward with #991.

**Comment by elemoine** [comment]
Sure, I was just experimenting. My primary goal was to understand this "vendoring" stuff.

**Pull request closed without merging**
