### PR TITLE
Change s3 bucket and create latest snap build.

### PR DESCRIPTION
**Pull request by nanliu**
* use different s3 bucket to allow DNS CNAME.
* create latest snap folder.
* use different latest url.

### CODE REVIEW

**Comment by nanliu** [comment]
See [travis build results](https://travis-ci.org/intelsdi-x/snap/jobs/147584409):

The short url: http://latest.snap.ci.snap-telemetry.io
Latest version: http://snap.ci.snap-telemetry.io/snap/latest/
Historic version: http://snap.ci.snap-telemetry.io/snap/{sha1}/

**Comment by mjbrender** [comment]
@nanliu LGTM - is this ready to merge or WIP?

**Comment by nanliu** [comment]
Joel suggested adding a branch name, which travis provides. Once the test passes on the build branch (since pr here doesn't actually trigger a deploy), it will be ready to merge.

**Comment by nanliu** [comment]
Ready for review and merge, see latest change:
https://travis-ci.org/intelsdi-x/snap/jobs/147814413#L243-L244

**Comment by jcooklin** [comment]
LGTM

**Pull request merged**
