### PR TITLE
Fix for Plugin loading ends with error when bool type from the cpolic…

### LINKED ISSUE #758: Plugin loading ends with error when bool type from the cpolicy package is used
Plugin loading ends with error "loading plugin:
gob: type not registered for interface: cpolicy.BoolRule"  when support for bool type from the cpolicy package is used.

I was trying to use support for bool type in the cpolicy package (added in #740) and I added something like this in GetConfigPolicy function for publisher plugin:
```go
cp := cpolicy.New()
config := cpolicy.NewPolicyNode()

r1, err := cpolicy.NewBoolRule("test1", false)
handleErr(err)
r1.Description = "description"

config.Add(r1)
cp.Add([]string{""}, config)
```

### PR DESCRIPTION
**Pull request by sandlbn**
Fixes #758 .

Summary of changes:
- Added cpolicy.BoolRule to the gob

Testing done:
- Yes

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by andrzej-k** [comment]
@sandlbn Thanks for this fix. This changes looks fine, however it could be even better if you could add some unit test(s) for this change - possibly in control/plugin/cpolicy/node_test.go

**Comment by sandlbn** [comment]
@andrzej-k I'm gonna do that Today.  :smiley_cat:

**Comment by geauxvirtual** [comment]
Rebase the branch against master as master includes  fix for the Go 1.4.3 testing issues.

**Comment by sandlbn** [comment]
This error never occurred on my local machine with Fedora 23 or Ubuntu 14.04 and go 1.6 

[iolie@irild016 snap]$ go version
go version go1.6 linux/amd64
$uname -a
Linux irild016.cslf1.intel.com 4.4.2-301.fc23.x86_64 #1 SMP Tue Feb 23 19:00:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux or 
Linux irild016.cslf1.intel.com 3.19.0-43-generic #49~14.04.1-Ubuntu SMP Thu Dec 31 15:44:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[make_test.txt](https://github.com/intelsdi-x/snap/files/181875/make_test.txt)

**Comment by jcooklin** [comment]
You would see the error if you tested locally with go1.4.3.

**Comment by sandlbn** [comment]
@jcooklin it's happening with go1.6 on the travis infra., I already rebased my PR to fix the problem with go 1.4.3 .

**Comment by geauxvirtual** [comment]
Please rebase the commit to start with `Fix #758:`

**Comment by geauxvirtual** [comment]
Commit message needs to start with `Fix #758:`

**Comment by jcooklin** [comment]
@sandlbn: After the commit message is updated as @geauxvirtual suggested above this LGTM.  
Note: #801 relates to this PR (if it merges first you will need to update your GOB registrations).

**Comment by sandlbn** [comment]
@jcooklin can u merge that ?

**Pull request merged**
