### PR TITLE
Updated plugin URL

### PR DESCRIPTION
**Pull request by thomastaylor312**
Updated the URL for NFS client to the new repo location

### CODE REVIEW

**Comment by jcooklin** [comment]
:ship:

**Comment by thomastaylor312** [comment]
@jcooklin I just rebased in master, so it should be up to date and ready to merge after CI finishes

**Comment by mjbrender** [comment]
Hey @thomastaylor312, I'd love to merge this but the status of "This branch is out-of-date with the base branch" is preventing me. Push in a rebase when time permits and we'll merge! Thanks.

**Comment by thomastaylor312** [comment]
@mjbrender Just rebased. Should be good to go when CI completes

**Comment by mjbrender** [comment]
LGTM! Merging - thanks again.

**Pull request merged**
