### PR TITLE
Fix issue 691

### PR DESCRIPTION
**Pull request by pjholmes**
Fix issue #691.

### CODE REVIEW

**Comment by tiffanyfj** [comment]
Huh, thought I had fixed those. Thanks! 
:+1:

**Comment by tiffanyfj** [comment]
@geauxvirtual I've had this issue before in a different file (you can see it in closed PRs)

For me: go1.5
```
./scripts/test.sh                                        ✹ ✭
Getting GoConvey if not found
Getting goimports if not found
Getting govet if not found
Getting cover if not found
gofmt
goimports
go vet
mgmt/rest/config.go:37: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:61: github.com/intelsdi-x/snap/mgmt/rest/rbody.PluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:103: github.com/intelsdi-x/snap/mgmt/rest/rbody.DeletePluginConfigItem composite literal uses unkeyed fields
mgmt/rest/config.go:145: github.com/intelsdi-x/snap/mgmt/rest/rbody.SetPluginConfigItem composite literal uses unkeyed fields
exit status 1
```

**Comment by mjbrender** [comment]
Hey @pjholmes - this is awesome. We spoke behind the scenes about asking you to update your base branch but never mentioned it here. Would you mind doing a quick rebase so we can merge? Ping @intelsdi-x/snap-maintainers when you're all set and one of us will get it faster this time :speedboat:

**Comment by geauxvirtual** [comment]
Cherry-picked this commit into PR #726. Closing this PR now as #726 has been merged.

**Pull request closed without merging**
