### PR TITLE
Updating plugins_catalog.md from plugins.yml

### PR DESCRIPTION
**Pull request by kindermoumoute**

### CODE REVIEW

**Comment by kindermoumoute** [comment]
@nanliu the maintainer of the syslog plugin is opsvision (see [metadata.yml](https://github.com/dishmael/snap-plugin-collector-syslog/blob/master/metadata.yml#L3), but the plugin is hosted on @dishmael repo. Pluginsync generated the maintainer link `[opsvision](https://github.com/dishmael)`, is it the intended behavior?

**Comment by nanliu** [comment]
I've raised this issue for further review among the maintainers. Let's not merge this change until we make a decision.

**Comment by dishmael** [comment]
@nanliu Would it be better for me to transfer the repo to our organization (OpsVision) versus my own space on GitHub (dishmael)?  I can transfer, update references, and then submit a new pull request if that is the appropriate behavior.  I just wanted to make sure to use our organization name instead of my name in the Plugin Catalog.

**Comment by kindermoumoute** [comment]
@dishmael that would probably make things less confusing. 👍

**Comment by dishmael** [comment]
@kindermoumoute ok, close this pull request and I will get things straightened out on my side. apologies for the confusion.

**Comment by dishmael** [comment]
@kindermoumoute I've created a new pull request #1459

**Pull request closed without merging**
