### PR TITLE
Documentation for tagging metrics via task manifest

### PR DESCRIPTION
**Pull request by marcin-krolik**
Summary of changes:
- added description of tagging mechanism in `collect` section
- modified `json` and `yaml` examples of task manifest

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by elemoine** [comment]
LGTM.

**Comment by IzabellaRaulin** [comment]
Documentation LGTM. 
@marcin-krolik , what do You think about adding some exemplary task manifest? What is more, I also noticed that snap-publisher-file doesn't publish metrics' tags. So, I prepared PR with that (https://github.com/intelsdi-x/snap/pull/1018). Could You look on that?

**Comment by marcin-krolik** [comment]
@IzabellaRaulin Sure, it's good idea.

**Comment by IzabellaRaulin** [comment]
LGTM

**Pull request merged**
