### PR TITLE
Switched the file publisher plugin to use JSON

### PR DESCRIPTION
**Pull request by thomastaylor312**
Summary of changes:
- Switches file publishing output from custom format to Marshalled metrics
- Cleans up a few missing comments and `fmt` usage

Testing done:
- Small unit tests pass
- Manual testing and validation

@intelsdi-x/snap-maintainers

### CODE REVIEW

**Comment by thomastaylor312** [comment]
This change was made after talking to @lynxbat about switching to a standard format

**Comment by IzabellaRaulin** [comment]
@thomastaylor312, after marshalling the whole **metricType** (includes core.Namespace struct),  what causes that metric's namespace is published in that way:

a) for non-dynamic metric
```json
"namespace": [
            {
                "Description": "",
                "Name": "",
                "Value": "intel"
            },
            {
                "Description": "",
                "Name": "",
                "Value": "mock"
            },
            {
                "Description": "",
                "Name": "",
                "Value": "bar"
            }
        ],
```
b) for dynamic metric
```json
"namespace": [
            {
                "Description": "",
                "Name": "",
                "Value": "intel"
            },
            {
                "Description": "",
                "Name": "",
                "Value": "mock"
            },
            {
                "Description": "name of the host",
                "Name": "host",
                "Value": "host0"
            },
            {
                "Description": "",
                "Name": "",
                "Value": "bar"
            }
        ],
```

I would suggest publishing only the value of namespace's elements:
```
"namespace":  "/intel/mock/bar"
```
```
"namespace":  "/intel/mock/host0/baz"
```
In this phase of workflow (publishing) only that carries useful information.

**Comment by jcooklin** [comment]
@All, how would you feel if we renamed this plugin to mock-file and added a new repo that contains the implementation for a supported file publisher plugin? 

I would argue that the plugins that exist in the snap repo today (mock, passthru and file)  are for testing purposes only and we should be clear about this distinction.  Renaming these plugins (passthru and file) to include the word mock and updating the readme about their purpose would make this distinction clear IMO.

**Comment by lynxbat** [comment]
+1

**Comment by thomastaylor312** [comment]
I am going to close this and open a new PR tomorrow that renames the plugin. I will also move this code to a new file publisher.

**Pull request closed without merging**
